FactoryGirl.define do
  factory :claim do
    company_id 1
pharmacy_id 1
customer nil
prescription nil
dispense nil
plan nil
rx_number 1
fill_number 1
plan_id_code 1
transmit_time "2016-10-14 10:21:14"
status 1
legacy_customer_id_number 1
active false
version "MyString"
transmission_code 1
authorization_number "MyString"
exceeds_percent false
dur_on_file false
date_filled "2016-10-14"
eligibility_override 1
origin_override 1
usual_customary_price "9.99"
level_of_service 1
primary_prescriber_dea_number "MyString"
cost_basis 1
total_submitted "9.99"
metric_decimal_quantity "9.99"
product_type 1
product_code "MyString"
incentive_amount "9.99"
cost_submitted "9.99"
fee_submitted "9.99"
percentage_tax_basis_submitted 1
tax_submitted "9.99"
communications_error_code "MyString"
header_response "MyString"
new_plan_number "MyString"
cost_paid "9.99"
contract_fee "9.99"
tax_paid "9.99"
total_paid "9.99"
accumulated_deductible "9.99"
deductible_left "9.99"
benefit_left "9.99"
amount_to_deductible "9.99"
copay_amount "9.99"
amount_for_product_selection "9.99"
exceeds_benefit_amount "9.99"
incentive_fee_paid "9.99"
service_fee_paid "9.99"
other_amount_fee_paid "9.99"
other_payor_amount_recognized "9.99"
amount_attributed_to_tax "9.99"
partial_copay_amount "9.99"
reimbursement_basis 1
percent_amount_tax_paid "9.99"
tax_rate_paid "9.99"
tax_basis_paid 1
help_desk_phone_number "MyString"
approved_message_count 1
approved_message_code ""
network_reimbursement_id "MyString"
reject_count 1
reject_code ""
reject_field_submitted ""
transmission_message "MyText"
other_coverage_code 1
denial_code ""
route_of_administration "MyString"
amount_processing_fee "9.99"
response_amount_coinsurance "9.99"
  end

end
