FactoryGirl.define do
  factory :customer do
    company_id 1
pharmacy_id 1
person_image nil
prescriber nil
facility nil
head_of_household_id 1
legacy_customer_id_number 1
active false
last_name "MyString"
first_name "MyString"
middle_name "MyString"
address1 "MyString"
address2 "MyString"
city "MyString"
state "MyString"
zip_code "MyString"
doc_u_dose false
doc_u_dose_group "MyString"
birthdate "2016-10-10"
ssn 1
phone_number 1
alternate_address false
gender 1
tax_exempt false
discount_name "MyString"
discount_pct "9.99"
nursing_home_resident false
price_based_pricing_schedule 1
childproof_cap false
generic_substitution false
last_rx_report_date "2016-10-10"
pregnant false
nursing false
height 1
weight 1
other_language 1
terminal false
deceased_date "2016-10-10"
needs_review false
signature_on_file false
hippa_signature_date "2016-10-10"
smoker false
location_code 1
residence_code 1
wellness false
ethnicity "MyString"
preferred_contact_method 1
account_number 1
memo "MyString"
notes "MyText"
special_label false
receive_text_msg false
auto_fill_maintenance_rx false
  end

end
