FactoryGirl.define do
  factory :prescription do
    company_id 1
pharmacy_id 1
customer nil
prescriber nil
item nil
rx_image nil
supervising_prescriber_id 1
rx_number 1
legacy_customer_id_number 1
legacy_prescriber_id_number 1
legacy_item_id_number 1
original_refills_prescribed 1
refills_prescribed 1
refills_left 1
original_total_quantity_prescribed "9.99"
quantity_remaining "9.99"
quantity_prescribed "9.99"
daily_quantity "9.99"
active false
rx_type 1
status 1
dea_schedule 1
dispense_as_written_code 1
certification_code 1
diagnosis_code "MyString"
diagnosis_code_qualifier 1
prior_authorization_number 1
prior_authorization_type 1
origin_code 1
refill_through_date "2016-10-11"
expiration_date "2016-10-11"
date_written "2016-10-11"
renewed_rx_number 1
renewed_rx_date "2016-10-11"
retail_auto_fill_type "MyString"
retail_auto_fill_next_date "2016-10-11"
last_fill_date "2016-10-11"
last_fill_number 1
last_fill_quantity "9.99"
last_fill_days_supply 1
last_fill_primary_paytype 1
last_fill_price "9.99"
last_fill_discount "9.99"
last_fill_legacy_item_id_number 1
doc_u_dose_rx false
on_docudose_calendar false
directions "MyText"
sig_frequency 1
notes "MyText"
counseling "MyText"
print_division_code "MyString"
print_on_prn false
print_on_mar false
print_on_po false
print_on_treatment false
print_on_flow false
pass_times ""
auto_fill_type 1
auto_fill_next_date "2016-10-11"
procycle_quantity_dispensed "9.99"
procycle_quantity_left "9.99"
start_date "2016-10-11"
stop_date "2016-10-11"
  end

end
