---
:concurrency: 2
:pidfile: tmp/pids/sidekiq.pid
staging:
  :concurrency: 2
production:
  :concurrency: 2
:queues:
  - ["claims_send_and_process_response", 1]
  - ["claims_preprocess_and_request_send", 1]
